//
//  HomeRouter.swift
//  jinyAssessment
//
//  Created by Jothi on 23/07/19.
//  Copyright (c) 2019 Widas. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


protocol HomeRoutingLogic
{
    func routerToBookList(title:String, queryStr:String)
}

protocol HomeDataPassing
{
    var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing
{
    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?
    
    // MARK: Routing
    
    func routerToBookList(title:String, queryStr:String)
    {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let bookListPage = storyboard.instantiateViewController(withIdentifier: "BookListViewController") as! BookListViewController
        bookListPage.titleStr = title
        bookListPage.queryStr = queryStr
        self.navigateToBookList(source: viewController!, destination: bookListPage)
    }
    
    // MARK: Navigating
    
    func navigateToBookList(source: HomeViewController, destination: BookListViewController)
    {
        source.show(destination, sender: nil)
    }
}
