//
//  HomeInteractor.swift
//  jinyAssessment
//
//  Created by Jothi on 23/07/19.
//  Copyright (c) 2019 Widas. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
    func fetchAllBookList()
}

protocol HomeDataStore
{
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
    var presenter: HomePresentationLogic?
    var worker: HomeWorker?
    
    // MARK: Get book list
    
    func fetchAllBookList() {
        
        worker = HomeWorker()
        worker?.getAllBooksListFromServer(callback: { (responseData) in
            self.presenter?.presentBookListSuccess(response: responseData)
        })
    }
}
