//
//  BookListInteractor.swift
//  jinyAssessment
//
//  Created by Jothi on 23/07/19.
//  Copyright (c) 2019 Widas. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BookListBusinessLogic
{
    func fetchBookDataBy(type: String, query: String)
}

protocol BookListDataStore
{
    //var name: String { get set }
}

class BookListInteractor: BookListBusinessLogic, BookListDataStore
{
    var presenter: BookListPresentationLogic?
    var worker: BookListWorker? = BookListWorker()
    //var name: String = ""
    
    // MARK: Do something
    
    func fetchBookDataBy(type: String, query: String) {
        worker = BookListWorker()
        worker?.fetchBookList(type, query: query,deleteBook:false, callback: { (res) in
            self.presenter?.presentBookList(response: res)
        })
    }
}
