//
//  BookListPresenter.swift
//  jinyAssessment
//
//  Created by Jothi on 23/07/19.
//  Copyright (c) 2019 Widas. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BookListPresentationLogic
{
    func presentBookList(response:[BookDetailsEntity])
}


class BookListPresenter: BookListPresentationLogic
{
    weak var viewController: BookListDisplayLogic?
    
    // MARK: Do something
    func presentBookList(response: [BookDetailsEntity]) {
        if response.count > 0 {
            self.viewController?.showBookList(viewModel: response)
        }else {
            self.viewController?.showFailureData()
        }
    }
    
}
