//
//  BookDetailViewController.swift
//  jinyAssessment
//
//  Created by Jothi on 23/07/19.
//  Copyright (c) 2019 Widas. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BookDetailDisplayLogic: class
{
}

class BookDetailViewController: UIViewController, BookDetailDisplayLogic
{
    var interactor: BookDetailBusinessLogic?
    var router: (NSObjectProtocol & BookDetailRoutingLogic & BookDetailDataPassing)?
    
    // MARK: Object lifecycle
    var bookId: String = ""
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = BookDetailInteractor()
        let presenter = BookDetailPresenter()
        let router = BookDetailRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        UpdateUI()
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    @IBOutlet weak var mainView: UIView!
    @IBOutlet weak var titleLbl: UILabel!
    @IBOutlet weak var bookCoverImg: UIImageView!
    @IBOutlet weak var authorLbl: UILabel!
    @IBOutlet weak var genreLbl: UILabel!
    @IBOutlet weak var aboutLbl: UILabel!
    
    
    private func UpdateUI()
    {
        BookDetailsDBRepo().fetchBookDetailBy(bookId) { (bookDetail) in
            if let _bookDetail = bookDetail {
                DispatchQueue.main.async {
                    self.titleLbl.text = _bookDetail.book_title
                    self.authorLbl.text = _bookDetail.author_name
                    self.aboutLbl.text = _bookDetail.publisher
                    self.genreLbl.text = _bookDetail.genre
                    self.bookCoverImg.cacheImage(urlString: _bookDetail.image_url)
                }
            }
        }
    }
    
    @IBAction func backButtonClicked(_ sender: UIButton) {
        _ = self.navigationController?.popViewController(animated: true)
    }
}
